CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL,
  email VARCHAR(128) DEFAULT NULL,
  phone VARCHAR(32) DEFAULT NULL,
  password_hash VARCHAR(255) NOT NULL,
  nickname VARCHAR(64) DEFAULT NULL,
  avatar_url VARCHAR(512) DEFAULT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  last_login_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_sys_user_username (username),
  UNIQUE KEY uk_sys_user_email (email),
  KEY idx_sys_user_status (status)
);

CREATE TABLE IF NOT EXISTS fl_family_space (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL,
  description VARCHAR(512) DEFAULT NULL,
  owner_user_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_fl_family_space_owner (owner_user_id)
);

CREATE TABLE IF NOT EXISTS fl_family_member (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  family_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  role VARCHAR(32) NOT NULL,
  joined_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_fl_family_member (family_id, user_id),
  KEY idx_fl_family_member_user_id (user_id),
  KEY idx_fl_family_member_role (family_id, role)
);

CREATE TABLE IF NOT EXISTS sys_operation_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT DEFAULT NULL,
  family_id BIGINT DEFAULT NULL,
  module VARCHAR(64) NOT NULL,
  action VARCHAR(64) NOT NULL,
  biz_type VARCHAR(64) DEFAULT NULL,
  biz_id BIGINT DEFAULT NULL,
  request_method VARCHAR(16) DEFAULT NULL,
  request_uri VARCHAR(512) DEFAULT NULL,
  ip_address VARCHAR(64) DEFAULT NULL,
  success TINYINT NOT NULL DEFAULT 1,
  error_message VARCHAR(1024) DEFAULT NULL,
  created_at DATETIME NOT NULL,
  KEY idx_sys_operation_log_user_id (user_id),
  KEY idx_sys_operation_log_family (family_id),
  KEY idx_sys_operation_log_biz (biz_type, biz_id),
  KEY idx_sys_operation_log_created_at (created_at)
);

CREATE TABLE IF NOT EXISTS fl_device_category (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  family_id BIGINT NOT NULL,
  name VARCHAR(64) NOT NULL,
  icon VARCHAR(128) DEFAULT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  system_default TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_fl_device_category_name (family_id, name),
  KEY idx_fl_device_category_family (family_id)
);

CREATE TABLE IF NOT EXISTS fl_device_asset (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  family_id BIGINT NOT NULL,
  category_id BIGINT DEFAULT NULL,
  name VARCHAR(128) NOT NULL,
  brand VARCHAR(128) DEFAULT NULL,
  model VARCHAR(128) DEFAULT NULL,
  serial_number VARCHAR(128) DEFAULT NULL,
  purchase_date DATE DEFAULT NULL,
  purchase_channel VARCHAR(128) DEFAULT NULL,
  purchase_price DECIMAL(12,2) DEFAULT NULL,
  location VARCHAR(128) DEFAULT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
  cover_file_id BIGINT DEFAULT NULL,
  remark VARCHAR(1024) DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_fl_device_asset_family (family_id),
  KEY idx_fl_device_asset_list (family_id, updated_at),
  KEY idx_fl_device_asset_category (category_id),
  KEY idx_fl_device_asset_status (family_id, status),
  KEY idx_fl_device_asset_brand (family_id, brand),
  KEY idx_fl_device_asset_purchase_date (purchase_date)
);

CREATE TABLE IF NOT EXISTS fl_warranty_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  family_id BIGINT NOT NULL,
  device_id BIGINT NOT NULL,
  warranty_type VARCHAR(32) NOT NULL DEFAULT 'OFFICIAL',
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  remind_days_before INT NOT NULL DEFAULT 30,
  service_phone VARCHAR(64) DEFAULT NULL,
  service_address VARCHAR(255) DEFAULT NULL,
  service_note VARCHAR(1024) DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_fl_warranty_record_family (family_id),
  KEY idx_fl_warranty_record_device (device_id),
  KEY idx_fl_warranty_record_end_date (family_id, end_date)
);

CREATE TABLE IF NOT EXISTS fl_file_resource (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  family_id BIGINT NOT NULL,
  biz_type VARCHAR(64) NOT NULL,
  biz_id BIGINT NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  storage_name VARCHAR(255) NOT NULL,
  storage_path VARCHAR(1024) NOT NULL,
  content_type VARCHAR(128) NOT NULL,
  file_size BIGINT NOT NULL,
  extension VARCHAR(32) DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_fl_file_resource_family (family_id),
  KEY idx_fl_file_resource_biz (family_id, biz_type, biz_id)
);

CREATE TABLE IF NOT EXISTS fl_manual_text_index (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  family_id BIGINT NOT NULL,
  device_id BIGINT NOT NULL,
  file_id BIGINT NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  content_text TEXT DEFAULT NULL,
  index_status VARCHAR(32) NOT NULL DEFAULT 'INDEXED',
  error_message VARCHAR(1024) DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_fl_manual_text_index_file (file_id),
  KEY idx_fl_manual_text_index_device (family_id, device_id),
  KEY idx_fl_manual_text_index_status (family_id, index_status)
);
CREATE TABLE IF NOT EXISTS fl_consumable_item (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  family_id BIGINT NOT NULL,
  device_id BIGINT NOT NULL,
  name VARCHAR(128) NOT NULL,
  brand VARCHAR(128) DEFAULT NULL,
  model VARCHAR(128) DEFAULT NULL,
  cycle_days INT NOT NULL,
  last_replaced_date DATE DEFAULT NULL,
  next_remind_date DATE DEFAULT NULL,
  remind_days_before INT NOT NULL DEFAULT 7,
  status VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
  enabled TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(1024) DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_fl_consumable_item_family (family_id),
  KEY idx_fl_consumable_item_device (device_id),
  KEY idx_fl_consumable_item_next_remind (family_id, next_remind_date),
  KEY idx_fl_consumable_item_status (family_id, status)
);

CREATE TABLE IF NOT EXISTS fl_consumable_replace_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  family_id BIGINT NOT NULL,
  consumable_id BIGINT NOT NULL,
  device_id BIGINT NOT NULL,
  replaced_date DATE NOT NULL,
  cost DECIMAL(12,2) DEFAULT NULL,
  note VARCHAR(1024) DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_fl_consumable_replace_family (family_id),
  KEY idx_fl_consumable_replace_consumable (consumable_id),
  KEY idx_fl_consumable_replace_device (device_id),
  KEY idx_fl_consumable_replace_date (replaced_date)
);

CREATE TABLE IF NOT EXISTS fl_maintenance_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  family_id BIGINT NOT NULL,
  device_id BIGINT NOT NULL,
  title VARCHAR(128) NOT NULL,
  fault_description VARCHAR(2048) NOT NULL,
  occurred_at DATETIME DEFAULT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  repair_channel VARCHAR(128) DEFAULT NULL,
  repair_contact VARCHAR(128) DEFAULT NULL,
  repair_cost DECIMAL(12,2) DEFAULT NULL,
  result_description VARCHAR(2048) DEFAULT NULL,
  completed_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_fl_maintenance_family (family_id),
  KEY idx_fl_maintenance_device (device_id),
  KEY idx_fl_maintenance_status (family_id, status),
  KEY idx_fl_maintenance_occurred_at (occurred_at),
  KEY idx_fl_maintenance_completed_at (family_id, completed_at)
);
CREATE TABLE IF NOT EXISTS fl_reminder_task (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  family_id BIGINT NOT NULL,
  user_id BIGINT DEFAULT NULL,
  reminder_type VARCHAR(64) NOT NULL,
  biz_type VARCHAR(64) NOT NULL,
  biz_id BIGINT NOT NULL,
  title VARCHAR(128) NOT NULL,
  content VARCHAR(1024) DEFAULT NULL,
  remind_at DATETIME NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  read_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_fl_reminder_family_status (family_id, status),
  KEY idx_fl_reminder_user_status (user_id, status),
  KEY idx_fl_reminder_remind_at (remind_at),
  KEY idx_fl_reminder_biz (biz_type, biz_id)
);

CREATE TABLE IF NOT EXISTS fl_notification_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  family_id BIGINT NOT NULL,
  user_id BIGINT DEFAULT NULL,
  reminder_id BIGINT DEFAULT NULL,
  channel VARCHAR(32) NOT NULL,
  title VARCHAR(128) NOT NULL,
  content VARCHAR(1024) DEFAULT NULL,
  recipient VARCHAR(512) DEFAULT NULL,
  status VARCHAR(32) NOT NULL,
  error_message VARCHAR(1024) DEFAULT NULL,
  attempt_count INT NOT NULL DEFAULT 0,
  next_retry_at DATETIME DEFAULT NULL,
  last_attempt_at DATETIME DEFAULT NULL,
  sent_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_fl_notification_family (family_id),
  KEY idx_fl_notification_user (user_id),
  KEY idx_fl_notification_status (status),
  KEY idx_fl_notification_dispatch (status, channel, next_retry_at, created_at),
  KEY idx_fl_notification_processing (status, last_attempt_at),
  KEY idx_fl_notification_sent_at (sent_at)
);

CREATE TABLE IF NOT EXISTS fl_ai_analysis (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  family_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  analysis_type VARCHAR(64) NOT NULL,
  biz_type VARCHAR(64) DEFAULT NULL,
  biz_id BIGINT DEFAULT NULL,
  provider VARCHAR(64) NOT NULL DEFAULT 'mock',
  model VARCHAR(128) DEFAULT NULL,
  input_summary VARCHAR(1024) DEFAULT NULL,
  result_json TEXT DEFAULT NULL,
  status VARCHAR(32) NOT NULL,
  error_message VARCHAR(1024) DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_fl_ai_analysis_family (family_id),
  KEY idx_fl_ai_analysis_user (user_id),
  KEY idx_fl_ai_analysis_biz (biz_type, biz_id),
  KEY idx_fl_ai_analysis_type (analysis_type)
);
